# Profile information
name: Mstinger
title: My Home
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/Mstinger.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/Mstinger" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: Mstinger

# Contact form
email: crc1764026842@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 3
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
